
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  namespace: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
        - name: py-app
          image: vmisra1989/my-python-app:9.0
          ports:
            - containerPort: 8081
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://elastic-apm-server.elastic-system.svc:8200"
            
            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: "Authorization=Bearer N3Rha0daZ0J5Z0RILVBja1d1Z3Q6U1NYU0RHU3B0RXYwNUowdTY3RTVldw=="
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=<app-name>,service.version=<app-version>,deployment.environment=production"

---
apiVersion: v1
kind: Service
metadata:
  name: py-app
  namespace: otel
spec:
  selector:
    app: py-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
