
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
  namespace: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
        - name: pyapp
          image: vmisra1989/py-app:10
          ports:
            - containerPort: 8081
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "elastic-apm-server.elastic-system.svc:8200/"
            
            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: "Authorization=Bearer Wl9sQ0xKZ0JWNlJDY3RrRTlvY0U6cWZ4X0lxX0dwQXE2TGptdkFNWEpnQQ=="
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=pyapp,service.version=1.0.0,deployment.environment=dev"

---
apiVersion: v1
kind: Service
metadata:
  name: pyapp
  namespace: otel
spec:
  selector:
    app: pyapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
